# Generated by Django 3.0.7 on 2020-06-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20200610_2321"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="product", options={"verbose_name_plural": "Produtos"},
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="products.Category",
                verbose_name="Categoria",
            ),
        ),
    ]
